(() => {
  'use strict';
  const gEl = document.getElementById('dl-g'), hEl = document.getElementById('dl-h'), pEl = document.getElementById('dl-p');
  const xResEl = document.getElementById('dl-res-x'), trResEl = document.getElementById('dl-res-trace');

  function modExp(base, exp, mod) {
    let res = 1n, b = BigInt(base) % BigInt(mod), e = BigInt(exp), m = BigInt(mod);
    while (e > 0n) {
      if (e % 2n === 1n) res = (res * b) % m;
      b = (b * b) % m;
      e = e / 2n;
    }
    return Number(res);
  }

  function extGCD(a, b) {
    if (b === 0) return { gcd: a, x: 1, y: 0 };
    const res = extGCD(b, a % b);
    return { gcd: res.gcd, x: res.y, y: res.x - Math.floor(a / b) * res.y };
  }

  function modInverse(a, m) {
    const { gcd: g, x } = extGCD(((a % m) + m) % m, m);
    return g === 1 ? ((x % m) + m) % m : null;
  }

  function update() {
    const g = parseInt(gEl.value, 10);
    const h = parseInt(hEl.value, 10);
    const p = parseInt(pEl.value, 10);

    if (isNaN(g) || isNaN(h) || isNaN(p) || g <= 1 || h < 1 || p <= 2) return;

    // Shanks' Baby-step Giant-step:
    // m = ceil(sqrt(p))
    const m = Math.ceil(Math.sqrt(p));

    // Baby steps: compute g^j mod p for j in [0, m-1] and store in hash table
    const table = new Map();
    let cur = 1;
    for (let j = 0; j < m; j++) {
      table.set(cur, j);
      cur = (cur * g) % p;
    }

    // Giant steps: g^(-m) mod p
    const g_m = modExp(g, m, p);
    const g_inv_m = modInverse(g_m, p);
    if (g_inv_m === null) return;

    let gamma = h;
    let solution_x = null;

    for (let i = 0; i < m; i++) {
      if (table.has(gamma)) {
        solution_x = i * m + table.get(gamma);
        break;
      }
      gamma = (gamma * g_inv_m) % p;
    }

    if (solution_x !== null) {
      const check = modExp(g, solution_x, p);
      xResEl.textContent = 'Discrete Log x = ' + solution_x;
      trResEl.textContent = g + '^' + solution_x + ' mod ' + p + ' = ' + check + (check === h ? ' ✓' : ' ✗') + ' | Block m = ' + m + ' (O(√p) Speedup)';
    } else {
      xResEl.textContent = 'NO SOLUTION FOUND';
      trResEl.textContent = 'Target h is not in the cyclic subgroup generated by g mod ' + p;
    }
  }

  [gEl, hEl, pEl].forEach(el => el.addEventListener('input', update));
  update();
})();